### ISSUE TITLE
iOS 中的多线程 | Yuki | Otaku

### ISSUE THREAD

**Issue by bewils** [bewils/bewils.github.io#16]
http://blog.bewils.cn/2017/08/26/iOS%E4%B8%AD%E7%9A%84%E5%A4%9A%E7%BA%BF%E7%A8%8B/

**Comment by zjzsliyang** [comment]
高产锐无敌。。

**Comment by bewils** [comment]
@zjzsliyang 毕竟全公司最菜(当然和懂科学的大佬没法比
