### ISSUE TITLE
CGAffineTransform 介绍 | Yuki | Otaku

### ISSUE THREAD

**Issue by bewils** [bewils/bewils.github.io#17]
http://blog.bewils.cn/2017/09/01/CGAffineTransform/

**Comment by zjzsliyang** [comment]
记得第一次看CGAffineTransform的时候觉得用这种矩阵来做动画虽然无敌但太鸡儿麻烦了😂

**Comment by bewils** [comment]
@zjzsliyang 您为什么什么都会 Orz

**Comment by zjzsliyang** [comment]
不不不 一看就觉得不会。。。
话说 我感觉下学期TAC可以进行每周学习活动叫做 深入理解锐无敌的博客
PS 大佬是怎么@bewils 的🌝 在Issue Page嘛？

**Comment by bewils** [comment]
@zjzsliyang 直接在评论框里@就行 应该是调了 API 只要这个人是 github 的注册用户就加上链接的
